# Generated by Django 3.1 on 2020-08-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0003_auto_20200830_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='prix',
            field=models.FloatField(max_length=10),
        ),
    ]
