# Generated by Django 3.1 on 2020-09-01 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0004_auto_20200830_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passenger.passenger')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passenger.trajet')),
            ],
        ),
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_places', models.IntegerField()),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passenger.personne')),
            ],
        ),
    ]
