# Generated by Django 3.1 on 2020-09-02 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0005_conducteur_voyage'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='conducteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='passenger.conducteur'),
            preserve_default=False,
        ),
    ]
