# Generated by Django 3.1 on 2020-09-03 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0007_auto_20200902_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='passenger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='passenger.passenger'),
        ),
    ]
